name: Deploy Sentinel Detection

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v3
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy detection
        run: |
          az deployment group create \
            --resource-group <sentinelrg> \
            --template-file detections/1.json
